version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mi_mongodb
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
